/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import connection.conn;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author manus
 */
public class frmMainMenu extends javax.swing.JFrame {
    static int userid;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public void getUserLoggedIn(int userId){
        try {
            sql = "SELECT * FROM users WHERE id='" + String.valueOf(userId) + "'";
            rs = stat.executeQuery(sql);
            
            while(rs.next()){
                String roles = rs.getString(5);
                if("Super Admin".equals(roles)){
                    menuPembelian.setVisible(true);
                    menuPenjualan.setVisible(true);
                    menuBarang.setVisible(true);
                    menuCustomer.setVisible(true);
                    menuSupplier.setVisible(true);
                }
            }
        } catch (Exception e) {
            System.out.println("error : " + e.toString());
        }
    }
    
    /**
     * Creates new form frmMainMenu
     */
    public frmMainMenu() {
        initComponents();
        
        userid = frmLogin.iduser;
        conn DB = new conn();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        this.getContentPane().setBackground(Color.white);
        getUserLoggedIn(userid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenu();
        menuBarang = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuPembelian = new javax.swing.JMenu();
        menuCustomer = new javax.swing.JMenu();
        menuPenjualan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuFile.setText("File");

        jMenuItem1.setText("Logout");
        menuFile.add(jMenuItem1);

        jMenuBar1.add(menuFile);

        menuSupplier.setText("Supplier");
        menuSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSupplierMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSupplier);

        menuBarang.setText("Barang");
        menuBarang.setName(""); // NOI18N

        jMenuItem2.setText("Data Barang");
        menuBarang.add(jMenuItem2);

        jMenuItem3.setText("Data Detail Barang");
        menuBarang.add(jMenuItem3);

        jMenuBar1.add(menuBarang);

        menuPembelian.setText("Pembelian");
        jMenuBar1.add(menuPembelian);

        menuCustomer.setText("Customer");
        jMenuBar1.add(menuCustomer);

        menuPenjualan.setText("Penjualan");
        menuPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPenjualanMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPenjualan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1485, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenjualanMouseClicked
        // TODO add your handling code here:
        frmPenjualan formPenjualan = new frmPenjualan();
        formPenjualan.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuPenjualanMouseClicked

    private void menuSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSupplierMouseClicked
        // TODO add your handling code here:
        frmSupplier formSupplier = new frmSupplier();
        formSupplier.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuSupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuBarang;
    private javax.swing.JMenu menuCustomer;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuPembelian;
    private javax.swing.JMenu menuPenjualan;
    private javax.swing.JMenu menuSupplier;
    // End of variables declaration//GEN-END:variables
}
